main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmain,name="show"),
    path('home',home,name="home"),
    path("profileMe",profileMe, name="profileMe"),
    path("photoMe",photoMe,name="photoMe"),
    path("introduceMe",introduceMe, name="introduceMe"),
    path('<str:id>',detail, name="detail"),
    path('new/',new, name="new"),
    path('create/',create, name="create"),
    path("edit/<str:id>",edit,name="edit"),
    path('<str:post_id>/<str:com_id>/edit_comment', edit_comment, name='edit_comment'),
    path("update/<str:id>",update,name="update"),
    path("delete/<str:id>",delete,name="delete"),
    path('<str:post_id>/create_comment', create_comment, name="create_comment"),
    path('updateComment/<str:post_id>/<str:com_id>',update_comment, name="update_comment"),
    path('deleteComment/<str:com_id>',delete_Comment, name = "delete_Comment"),
    path('like_toggle/<int:post_id>/',like_toggle,name="like_toggle"), #좋아요 기능 
    path('dislike_toggle/<int:post_id>/',dislike_toggle,name="dislike_toggle"), #좋아요 기능 
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # settings 가져오기 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls')), #urls.py 관리하는법 
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name ="users"
urlpatterns=[
    path('mypage/<int:id>',views.mypage,name="mypage"),
    path('follow<int:id>',views.follow, name="follow"),
] 

users/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.dispatch import receiver
from django.db.models.signals import post_save

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE) 
    followings=models.ManyToManyField("self", related_name="followers", symmetrical=False)
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created: 
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
 

# from django.db import models
# from django.contrib.auth.models import User 
# from django.dispatch import receiver
# from django.db.models.signals import post_save

# class Profile(models.Model):
#     user = models.OneToOneField(User,on_delete=models.CASCADE)
#     followings = models.ManyToManyField("self",related_name="followers",symmetrical=False)

# @receiver(post_save,sender = User)
# def create_user_profile(sender,instance,created,**kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# @receiver(post_save,sender=User)
# def save_user_profile(sender,instance,**kwargs):
#     instance.profile.save()

users/views.py
from django.shortcuts import get_object_or_404, redirect, render
from main.models import Post
from django.contrib.auth.models import User 

def mypage(request, id):
    user = get_object_or_404(User,pk=id)
    context={
        'user':user,
        'posts':Post.objects.filter(writer=user),
        'followings':user.profile.followings.all(),
        'followers':user.profile.followers.all(),
    }
    return render(request,'users/mypage.html',context) 

def follow(request,id):
    user = request.user #로그인한 유저(A)
    followed_user = get_object_or_404(User,pk=id) #팔로우/언팔로우 할 유저 (B)
    is_follower = user.profile in followed_user.profile.followers.all() #B의 팔로워 목록에 A가 있는지 판단 
    if is_follower:
        user.profile.followings.remove(followed_user.profile) #remove -> A의 팔로잉 목록에서 B삭제 
    else:
        user.profile.followings.add(followed_user.profile) #A팔로잉 목록에서 B추가 
    return redirect('users:mypage',followed_user.id)

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
    .follow{
        margin: 20px;
    }
    .post_list
    {
        text-align: center;
    }
    .list_follow
    {
        margin: 10px;
        font-size: 20px;
        font-weight: 600;
        color: wheat;
    }
    a:visited{
        color: rgb(155, 155, 155);
    }
    a:link{
        color : whitesmoke;
        text-decoration: none;
    }
    .nav__bar{
    position: fixed;
    bottom: 0;
    width: 100%;
    background-color: #ffffff;
    padding: 20px 50px;
    box-sizing : border-box;
    border-top: 1px solid rgba(121,121,121,0.3);
}

.nav__list{
    display:flex;
    justify-content: space-between;
}

.nav__link{
    position: relative;
    color: #2e363e;
}

.nav__btn{
    margin-top: 5px;
}
.user_name{
    font-weight: 600;
}


@keyframes appear{
    from{

opacity: 0;
    }to{
        opacity: 1;
transform: none;
    }
}
.nav__btn{
    transform: translateY(50px);
    opacity: 0;
animation: appear 0.5s ease-in-out forwards;
}
.nav__btn:nth-child(2){
animation-delay: 0.5s;
}
.nav__btn:nth-child(3){
    animation-delay: 0.7s;

}
.nav__btn:last-child{
    animation-delay: 1.0s;
}
.status-bar{
    position: fixed;
    top:0px;
    width: 100%;
    display: flex;
    justify-content: center;
    padding: 5px 3px;
    font-weight: 600;
 
}
.status-bar__column{
    width: 33%;
}
.status-bar__column:nth-child(2){
    display: flex;
    justify-content: center;
}
.status-bar__column:last-child{
    display: flex;
    justify-content: flex-end;
    align-items: center;
}

.status-bar__column.fa-battery-full{
    margin : 0px 4px;
}
.status-bar__column:first-child span{
    margin-right: 5px;
}



</style>
<nav class=nav__bar>
    <ul class="nav__list">
        <li class="nav__btn"><a class="nav__link" href="{% url  'main:show' %}"><p></p><i class="fas fa-home fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:introduceMe'%}"><i class="far fa-file fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:photoMe'%}"><i class="far fa-image fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:profileMe'%}"><i class="fas fa-user fa-2x"></i></a></li>
    </ul>
</nav>
<div class="container">
    <h1>{{user.username}}</h1>
    <!-- 다른 사람의 프로필에 들어온 경우에만 팔로/언팔 버튼 보임 -->
    {% if request.user != user %} 
        {% if request.user.profile in user.profile.followers.all %}
            <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-outline-info">언팔로우</button></a>
        {% else %}
            <a href="{% url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
        {% endif %}
    {% endif %}
    <div class="container follow">
        <h3>팔로워 {{ user.profile.followers.count }}명 </h3>
        <div class="list_follow">
            {% for follower in user.profile.followers.all %}
                <a href="{% url 'users:mypage' follower.user.id %}">{{ follower.user.username }}</a>
            {% endfor %}
        </div>            

        <h3>팔로잉 {{ user.profile.followings.count }}명 </h3>
        <div class="list_follow">
        {% for following in user.profile.followings.all %}
            <a href="{% url 'users:mypage' following.user.id %}">{{ following.user.username }}</a>
        {% endfor %}
        </div>
    </div>

    
    <div class="post_list"> 
        <h3> {{user.username}}님이 작성한 게시글</h3>
        <div class="list_follow">
        {% for post in posts %}
        
        <a href="{% url 'main:detail' post.id %}">{{post.title}}</a><hr>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}