main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmain,name="show"),
    path('home',home,name="home"),
    path("profileMe",profileMe, name="profileMe"),
    path("photoMe",photoMe,name="photoMe"),
    path("introduceMe",introduceMe, name="introduceMe"),
    path('<str:id>',detail, name="detail"),
    path('new/',new, name="new"),
    path('create/',create, name="create"),
    path("edit/<str:id>",edit,name="edit"),
    path('<str:post_id>/<str:com_id>/edit_comment', edit_comment, name='edit_comment'),
    path("update/<str:id>",update,name="update"),
    path("delete/<str:id>",delete,name="delete"),
    path('<str:post_id>/create_comment', create_comment, name="create_comment"),
    path('updateComment/<str:post_id>/<str:com_id>',update_comment, name="update_comment"),
    path('deleteComment/<str:com_id>',delete_Comment, name = "delete_Comment"),
    path('like_toggle/<int:post_id>/',like_toggle,name="like_toggle"), #좋아요 기능 
    path('dislike_toggle/<int:post_id>/',dislike_toggle,name="dislike_toggle"), #좋아요 기능 
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # settings 가져오기 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls')), #urls.py 관리하는법 
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name ="users"
urlpatterns=[
    path('mypage/<int:id>',views.mypage,name="mypage"),
    path('follow<int:id>',views.follow, name="follow"),
] 

main/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/",blank=True,null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set',through='Like')
    dislike_user_set = models.ManyToManyField(User, blank=True, related_name='dislikes_user_set',through='Dislike')

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def dislike_count(self):
        return self.dislike_user_set.count()
        
    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:10] ## 적절량 짜르기 

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('user', 'post'))

#싫어요 모델
class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'post'))

main/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import *
from django.utils import timezone
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

import json

def showmain(request):
    return render(request, 'main/mainpage.html')
  
def introduceMe(request): #소개 페이지 
    return render(request, 'main/introduce.html')

def photoMe(request): # 사진 
    return render(request, 'main/photo.html')
 
def profileMe(request): # 프로파일 !
    posts = Post.objects.all()
    return render(request, 'main/profile.html',{'posts':posts})

def home(request):
    userName = request.GET['name']
    return render(request, 'main/home.html',{'userName':userName})

def detail(request,id):
    post = get_object_or_404(Post,pk = id) #id로 각 개체 구분, post에 페이지 가져와서 저장
    all_comments = post.comments.all().order_by('-create_at')
    return render(request,'main/detail.html',{'post':post, 'comments':all_comments})

def new(request):
    return render(request,'main/new.html')

def create(request):
    new_post =Post()
    new_post.title = request.POST['title']
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image') #이미지 
    new_post.save()
    return redirect('main:detail',new_post.id)   

def edit(request, id):
    edit_Post = Post.objects.get(id=id)
    return render(request,"main/edit.html",{"Post":edit_Post})

#댓글 수정하기 
def edit_comment(request, post_id, com_id):
    edit_post=Post.objects.get(id=post_id)
    edit_comment=Comment.objects.get(id=com_id)
    return render(request, 'main/edit_comment.html',{'post': edit_post, 'comment':edit_comment})


#댓글 업데이트 시키기
def update_comment(request,post_id,com_id):
    if request.method =='POST':
        post= get_object_or_404(Post,pk=post_id)
        comment=Comment.objects.filter(pk=com_id)
        curUser=request.user
        com_content=request.POST.get('content')
        comment.update(content=com_content,writer=curUser,post=post)
    return redirect('main:detail',post_id)

#업데이트
def update(request,id):
    update_Post = Post.objects.get(id=id)
    update_Post.title = request.POST['title']
    update_Post.writer = request.user
    update_Post.pub_date = timezone.now()
    update_Post.body = request.POST['body']
    # update_Post.image = request.FILES['image']
    update_Post.save()
    return redirect('main:detail', update_Post.id)

def delete(request, id):
    delete_Post = Post.objects.get(id=id) #모든 객체 가지고온다 
    delete_Post.delete() # 삭제 ~ 
    return redirect("main:profileMe") #삭제후 보여지는 페이지 이동 

#댓글 삭제 함수 
def delete_Comment(request,com_id):
    delete_comment = Comment.objects.get(id=com_id)
    delete_comment.delete()
    return redirect('main:profileMe')

def create_comment(request, post_id):
	if request.method == "POST":
		post = get_object_or_404(Post, pk=post_id)
		current_user = request.user
		comment_content = request.POST.get('content')
		Comment.objects.create(content=comment_content, writer=current_user, post=post)
	return redirect('main:detail', post_id)    


@require_POST
@login_required
def like_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_like, post_like_created = Like.objects.get_or_create(user=request.user, post=post)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"
    
    context = {
        "like_count":post.like_count,
        "result":result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

@require_POST
@login_required
def dislike_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_dislike, post_dislike_created = Dislike.objects.get_or_create(user=request.user, post=post)

    if not post_dislike_created:
        post_dislike.delete()
        result = "dislike_cancel"
    else:
        result = "dislike"
    
    context = {
        "dislike_count":post.dislike_count,
        "result":result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

main/templates/main/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>
.edit{
    text-align: right;
    margin: auto;
}
.comment_form{
    margin: 20px;
    margin-top: 30px;
}
img{
    width: 30%;
    height: 30%;
}
</style>
<nav class=nav__bar>
    <ul class="nav__list">
        <li class="nav__btn"><a class="nav__link" href="{% url  'main:show' %}"><p></p><i class="fas fa-home fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:introduceMe'%}"><i class="far fa-file fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:photoMe'%}"><i class="far fa-image fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:profileMe'%}"><i class="far fa-user fa-2x"></i></a></li>
    </ul>
</nav>`

<h1>게시글 제목 : {{post.title}}</h1>
{% if blog.writer %}
    {% if 'user' in blog.writer.username %}
        <h3>작성자 : {{ blog.writer.last_name }} {{ blog.writer.first_name }}</h3>
    {% else %}
        <h3>작성자 : {{ blog.writer }}</h3>
    {% endif %}
{% endif %}

<h1 style="margin: 10px 0px;">작성자 : {{post.writer}}</h1>
날짜 : {{post.pub_date}}
<hr>
<!-- if문 추가하기 -->
{% if post.image %}
<p style="text-align: center;">사진 : <img src="{{post.image.url}}" alt="사진"></p>
{% endif %}
<p>내용 : {{post.body}}</p>
<div class="edit">
    <a href="{% url 'main:edit' post.id %}">수정하기</a>
    <a href="{% url 'main:delete' post.id %}">삭제하기</a>
</div>
<hr>

<!-- 하트표시 -->
<span href="#" class="like" name ="{{post.id}}" value="Like"> 
    {% if user in post.like_user_set.all %}
        <div class="alt-service-icon">
            <i class="fas fa-heart" id ="like-icon" style="color:red;"></i>
         </div>   
    {% else %}
        <div class="alt-service-icon">
             <i class="far fa-heart" id ="like-icon" style="color:red;"></i> 
        </div>
     {% endif %}
<!-- 좋아요개수 -->
     <span id="count-{{ post.id }}" class="alt-services-title font-alt"> 
        좋아요 
        {% if post.like_count == 0 %} 
            0개 
        {% else %}
            {{ post.like_count }}개
        {% endif %}
     </span>
</span>

<!-- 싫어요표시 -->
<span href="#" class="dislike" name ="{{post.id}}" value="Dislike"> 
    {% if user in post.dislike_user_set.all %}
        <div class="alt-service-icon">
            <i class="fas fa-thumbs-down" id ="dislike-icon" style="color:whitesmoke;"></i>
         </div>   
    {% else %}
        <div class="alt-service-icon">
             <i class="far fa-thumbs-down" id ="dislike-icon" style="color:whitesmoke;"></i>
        </div>
     {% endif %}
<!-- 싫어요개수 -->
     <span id="Discount-{{ post.id }}" class="alt-services-title font-alt"> 
        싫어요 
        {% if post.dislike_count == 0 %} 
            0개 
        {% else %}
            {{ post.dislike_count }}개
        {% endif %}
     </span>
</span>

</div>


<!-- 댓글생성 -->
<div class="comment_form">
	<form action="{%url 'main:create_comment' post.id%}" method="POST">
		{%csrf_token%}
		<textarea name="content" placeholder="댓글내용입력"></textarea>
		<input type="submit" value="확인">
	</form>
</div>


<div>
    {% for comment in comments %}
    <div>
        작성자 : <a href="{% url 'users:mypage' post.writer.id %}">{{comment.writer}}</a><br>
        내용 : {{comment.content}}
        <br>
        <a href="{%url 'main:edit_comment' post.id comment.id %}" style="float: right; margin-right: 10px;">수정하기</a>
        <a href="{%url 'main:delete_Comment' comment.id %}" style="float: right; margin-right: 10px;">삭제하기</a>
        <hr>
    </div>
    {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<!-- 좋아요 스크립트 -->
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            type:"POST",
            url : "{% url 'main:like_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType:"json",
            
            success: function(response){

                if (response.like_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "like"){
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-heart');
                    }
                    else{
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-heart');
                    }

                    $('#count-{{ post.id }}').html('좋아요 '+response.like_count+'개');
                }
            },

            error: function(request, status, error){
                alert("로그인이 필요합니다.")
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         })
    })
 </script>

 <!-- 싫어요 스크립트 -->
 <script>
    $(".dislike").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            url : "{% url 'main:dislike_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            type:"POST",
            dataType:"json",
            
            success: function(response){

                if (response.dislike_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "dislike"){
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fas fa-thumbs-down');
                    }
                    else{
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('far fa-thumbs-down');
                    }

                    $('#Discount-{{ post.id }}').html('싫어요'+response.dislike_count+'개');
                }
            },

            error: function(request, status, error){
                alert("로그인이 필요합니다.")
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         })
    })
 </script>
{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<h1>글 수정하기</h1>
	<form action="{%url 'main:update' Post.id %}" method="Post">
		{%csrf_token%}
		<p>제목 : <input type="text" name="title" value ="{{Post.title}}"></p>
		<p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{Post.body}}</textarea></p>
		<p>사진 : <input type="file" name ="image">{{Post.image}}</p>
		
		<button type="submit">제출</button>
	</form>
</div>
{% endblock %}

main/templates/main/edit_comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
	<form action="{%url 'main:update_comment' post.id comment.id%}" method="POST">
		{%csrf_token%}
		<textarea name="content" placeholder="댓글입력"></textarea>
		<input type="submit" value="제출">
	</form>
</div>


{% endblock %}

main/templates/main/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<nav class=nav__bar>
    <ul class="nav__list">
        <li class="nav__btn"><a class="nav__link" href="{% url  'main:show' %}"><p></p><i class="fas fa-home fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:introduceMe'%}"><i class="far fa-file fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:photoMe'%}"><i class="far fa-image fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nasv__link" href="{% url 'main:profileMe'%}"><i class="far fa-user fa-2x"></i></a></li>
    </ul>
</nav>


<main class="main-title" style="text-align: center;">
<p style="font-size: 30px; padding-bottom: 10px;"> 환영합니다 !! </p>
<h1 style="font-weight: 600;">{{userName}}님 !! </h1>

<div class="main_introduce">
   <h6>이 페이지를 사용하는 방법은 간단합니다 ! </h6>
   <br>
    <div class="main_icon_introduce " style="text-align: center; line-height: 2em;">
        <i class="fas fa-home fa-2x"></i><p>이름 입력 페이지입니다 ! </p>
        <i class="far fa-file fa-2x"></i><p>자기소개 페이지 입니다 !</p>
        <i class="far fa-image fa-2x"></i><p>저의 갤러리입니다 ! </p>
        <i class="far fa-user fa-2x"></i><p>블로그 글목록/글작성이 가능한 페이지 입니다 !</p>
        <br>
    </div>
    <div class="main_main">
       현재 페이지는 설명페이지입니다!!
   </div>
</div>
</main>


{% endblock %}

main/templates/main/introduce.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
    .farewell{
        font-size: 30px;
        margin-top: 15px;
        font-weight: 600;
    }
</style>
<nav class=nav__bar>
    <ul class="nav__list">
        <li class="nav__btn"><a class="nav__link" href="{% url  'main:show' %}"><p></p><i class="fas fa-home fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:introduceMe'%}"><i class="fas fa-file fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:photoMe'%}"><i class="far fa-image  fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:profileMe'%}"><i class="far fa-user fa-2x"></i></a></li>
    </ul>
</nav>
<body>
    <div class = "centerfor">
    <header>
        <div class="title text-flicker-in-glow" style="transform: translate(0,-20px);">
            <h2>저를 소개합니다 !</h2>
        </div>
    </header>
    <section class="">
        <div class="name">
            <span class="title_">이름 :<span>
            <span class="self">서희찬</span>
        </div>
        <div class="age">
            <span class="title_">나이 :<span>
            <span class="self">23살</span>
        </div>
        <div class="department">
            <span class="title_">전공/학번/학년 : <span>
            <span class="self">멀티미디어 공학과/19학번/1학년</span>
        </div>
        <div class="introduce_me" style="line-height: 1.3em; padding-top: 37px;">
            <span calss="me">안녕하세요 ! 독서와 헬스를 취미로 삼고 코딩은 공부중인 서희찬입니다.</br>저는 군대 전역을 한지 얼마안되어서 학교는 휴학상태중입니다.</br>저는 모든일에는 끝까지 !! 책임을 지는 성격이고, 한번 잡은 목표는 이루기위해 최선을 다하는 스타일입니다.</br>(그렇기에...수능도 3번쳤답니다..크흑 ㅠㅜㅋ)
            </br>성격은 내성적이여서 낯을 많이 가리지만 친해진다면! 매우 외향적이게된답니다!!(아마도..아닐수도있습니다...)<br/>현재는 저의 꿈 졸업전에 스타트업을 시작하기 위해서 많은 것을 배우기 위해 멋쟁이사자처럼을 열심히 활동중입니다 ! </span>
            
        </div>
        <div class="farewell">
            <h2>감사합니다 !</br>m(_ _)m</h2>
        </div>

    </section>
</div>

</body>
{% endblock %}

main/templates/main/mainpage.html
<div style="text-align: center;">
    <br>
    <h1>안녕하세요 ! </h1>
    <h1>방문자의 이름을 입력해주세요!</h1>
    <br>
    <form action="home" >
        <label for="nameInput">이름 : </label>
        <input id="nameInput" name="name" required>
        <input type="submit" value="제출">
    </form>
    <br>
    <h4>제출해주시면 Chans Cosmos 페이지가 나온답니당~~!!~!!</h4>
</div>

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<h1>글 작성하기</h1>
	<form action="{%url 'main:create'%}" method="post" enctype="multipart/form-data">
		{%csrf_token%}
		<p>제목 : <input type="text" name="title"></p>
		<p>사진 : <input type="file" name ="image"></p>
		<p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
		<button type="submit">제출</button>
	</form>
</div>
{% endblock %}

main/templates/main/photo.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<style>
    figcaption {
  color: #fff;
  background: rgba(121, 119, 119, 0.5);
  padding: 1em;
  line-height: 1;
}
figure {
  margin: 0;
  line-height: 0;
}
/* Alignment styles */
body {
  display: flex;
  justify-content: center;
  align-items: center;
  font-family: system-ui;
}
* {
  box-sizing: border-box;
}
.part1{
  display: block;
}
</style>
<nav class=nav__bar>
    <ul class="nav__list">
        <li class="nav__btn"><a class="nav__link" href="{% url  'main:show' %}"><p></p><i class="fas fa-home fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:introduceMe'%}"><i class="far fa-file fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:photoMe'%}"><i class="fas fa-image fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:profileMe'%}"><i class="far fa-user fa-2x"></i></a></li>
    </ul>
</nav>


<section class="part1" style="text-align: center;">
    <div class="introduce_photo">
        <p style="font-weight: 600; font-size: larger; transform: translate(0,-20px);">
            저는 사진을 찍는것과 찍히는것을 되게 좋아하는데요!!!
            <h1>그 중에서 저가 마음에 드는... 저의 사진과 예쁜 우리집 앞에 저의 갬성이 가득 담긴! 사진을 보여드릴께요 ! </h1>
        </p>
        <figure>
            <img src="{%static 'images/me1.jpg' %}" height="200"; width="150" alt="으아" style="margin-top: 30px;">
            <img src="{%static 'images/me6.jpg' %}" height="200"; width="150" alt="으어" style="margin-top: 30px;">
            <img src="{%static 'images/me7.jpg' %}" height="200"; width="150" alt="집 앞" style="margin-top: 30px;">
            <img src="{%static 'images/me4.jpg' %}" height="200"; width="150" alt="으어엉" style="margin-top: 30px;">
            <img src="{%static 'images/me3.jpg' %}" height="200"; width="150" alt="가나다라" style="margin-top: 30px;">
            <img src="{%static 'images/me2.jpg' %}" height="200"; width="150" alt="집 앞" style="margin-top: 30px;">
            <figcaption>저의 사진과 집 앞!!(코시국 이라서 마스크쓴 사진밖에 없어서 아쉽네요 ㅠㅠ )</figcaption>
          </figure>
    </div>
        
</section>

{% endblock %}

main/templates/main/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
    .blog{
        text-align: center;
        line-height: 1.2em;
    }
    .Blog_intro{
    text-align: center;
    font-size: 50px;
    padding-bottom: 20px;
    transform: translate(0,-5px);
    }
    .blog_title{
        font-size: 30px;
        font-weight: 600;
        margin-bottom: 9px;
    }
    .blog a:link{
        color: blue;
    }
    .blog a:hover{
        color: black;
    }
    .blog a:active{
        color: red;
    }
    .blog a:visited{
      color : rgba(185, 221, 215, 0.5);

}

     
</style>

<nav class=nav__bar>
    <ul class="nav__list">
        <li class="nav__btn"><a class="nav__link" href="{% url  'main:show' %}"><p></p><i class="fas fa-home fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:introduceMe'%}"><i class="far fa-file fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:photoMe'%}"><i class="far fa-image fa-2x"></i></a></li>
        <li class="nav__btn"><a class="nav__link" href="{% url 'main:profileMe'%}"><i class="fas fa-user fa-2x"></i></a></li>
    </ul>
</nav>


<body>
    <h1 class= "Blog_intro" style="font-size: 40px; font-weight: 600;">Blog</h1>
    <section class="blog">
        <!-- 로그인 됐을때 -->
        {% if user.is_authenticated %}
            {% if post.writer %}
                <h2>닙냐뇽</h2>
            {% else %}
            닙냐농
                <h2 style="font-size: 30px; font-weight: 600; margin: 20px;"><a href="{%url 'main:new'%}">글쓰기</a></h2>
            {% endif %}
        <h1 style="font-size: 20px; font-weight: 600;">글 목록</h1>
        <br>
        <div>   
            <!-- 작성된 포스트 나열  -->
            {% for post in posts%}
            <div>
                <h3>제목 : {{post.title}}</h3>
                {% if post.writer %}
                    {% if 'user' in post.writer.username and post.writer.username != 'user' %}
                        작성자 : <a href="{% url 'users:mypage' post.writer.id %}"> {{ post.writer.last_name }} {{ post.writer.first_name }}</a>
                    {% else %}
                        작성자 : <a href="{% url 'users:mypage' post.writer.id %}"> {{ post.writer }}</a>
                    {% endif %}
                {% else %}
                    작성자 : 알 수 없음
                {% endif %}
                <a href="{% url 'main:detail' post.id %}">....자세히</a>
                <br>
            </div>
            <br>
            {% endfor %}
        </div>
        {% else %}
        <h3>로그인 후 이용 가능</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
        {% endif %}
        
        
    </section>

</body>
{% endblock %}